name: Auto Sync from LmeSzinc (Keep My Changes)

on:
  schedule:
    - cron: '*/30 * * * *'  # 每半小时运行
  workflow_dispatch:        # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream master

      - name: Merge upstream changes (preserve mine)
        run: |
          git checkout master
          git merge upstream/master --no-edit -X ours || true
          git push origin master
