name: Sync Fork from Two Upstreams (Only When Upstream Updates)

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # ===== 第一个 upstream =====
      - name: Add first upstream (LmeSzinc)
        run: |
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream

      - name: Check updates from LmeSzinc
        id: check1
        run: |
          if git rev-list HEAD...upstream/master --count | grep -q '^[1-9]'; then
            echo "has_update=true" >> $GITHUB_OUTPUT
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
          fi

      # ===== 第二个 upstream =====
      - name: Add second upstream (guoh064)
        run: |
          git remote add upstream2 https://github.com/guoh064/AzurLaneAutoScript.git
          git fetch upstream2

      - name: Check updates from guoh064
        id: check2
        run: |
          if git rev-list HEAD...upstream2/main --count | grep -q '^[1-9]'; then
            echo "has_update=true" >> $GITHUB_OUTPUT
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
          fi

      # ===== 合并 + 推送 =====
      - name: Merge from LmeSzinc (keep my changes and detect conflicts)
        if: steps.check1.outputs.has_update == 'true'
        id: merge1
        run: |
          git checkout master
          if ! git merge upstream/master --strategy-option ours --no-edit; then
            echo "conflict_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge from guoh064 (keep my changes and detect conflicts)
        if: steps.check2.outputs.has_update == 'true'
        id: merge2
        run: |
          if ! git merge upstream2/main --strategy-option ours --no-edit; then
            echo "conflict_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes back to my fork
        if: steps.check1.outputs.has_update == 'true' || steps.check2.outputs.has_update == 'true'
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ===== 邮件通知 =====
      - name: Email notify if conflicts
        if: steps.merge1.outputs.conflict_detected == 'true' || steps.merge2.outputs.conflict_detected == 'true'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            --method POST \
            --field event_type="sync_conflict_detected" \
            --field client_payload='{"message":"在同步 upstream 时发生冲突（已保留你的改动），请手动检查。"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
